### ISSUE TITLE
3Sum

### ISSUE THREAD

**Issue by mahakmandlecha** [mahakmandlecha/LeetCoding-Challenge#1]
Given an array nums of n integers, are there elements a, b, c in nums such that a + b + c = 0? Find all unique triplets in the array which gives the sum of zero.

Notice that the solution set must not contain duplicate triplets.

Input: nums = [-1,0,1,2,-1,-4]
Output: [[-1,-1,2],[-1,0,1]]

**Comment by amitagarwalaa57** [comment]
please assign me task i can solve.

**Comment by Aditi-Roy-coder** [comment]
Please assign this task to me.
