### ISSUE TITLE
Two City Scheduling

### ISSUE THREAD

**Issue by mahakmandlecha** [mahakmandlecha/LeetCoding-Challenge#14]
A company is planning to interview 2n people. Given the array costs where costs[i] = [aCosti, bCosti], the cost of flying the ith person to city a is aCosti, and the cost of flying the ith person to city b is bCosti.

Return the minimum cost to fly every person to a city such that exactly n people arrive in each city

Input: costs = [[10,20],[30,200],[400,50],[30,20]]
Output: 110
Explanation: 
The first person goes to city A for a cost of 10.
The second person goes to city A for a cost of 30.
The third person goes to city B for a cost of 50.
The fourth person goes to city B for a cost of 20.

The total minimum cost is 10 + 30 + 50 + 20 = 110 to have half the people interviewing in each city.

**Comment by DevanshiJain** [comment]
Hey, I wish to contribute to this issue. Can you please assign this to me?

**Comment by Suhani028** [comment]
Can you please assign me this in JAVA!

**Comment by Nancey12** [comment]
I want to contribute in python.
