### ISSUE TITLE
All Elements in Two Binary Search Trees

### ISSUE THREAD

**Issue by mahakmandlecha** [mahakmandlecha/LeetCoding-Challenge#15]
Given two binary search trees root1 and root2.

Return a list containing all the integers from both trees sorted in ascending order.

Input: root1 = [2,1,4], root2 = [1,0,3]
Output: [0,1,1,2,3,4]

**Comment by Sankalpagrawal** [comment]
Hi, I want to take up this issue. Request you to assign this to me.

**Comment by Suhani028** [comment]
Hey, please assign me to contribute in JAVA!

**Comment by Nancey12** [comment]
Let me contribute in python.

**Comment by mahakmandlecha** [comment]
I'm sorry!! someone has already created a pr for it..
