### ISSUE TITLE
Edit Distance

### ISSUE THREAD

**Issue by mahakmandlecha** [mahakmandlecha/LeetCoding-Challenge#2]
Given two words word1 and word2, find the minimum number of operations required to convert word1 to word2.

You have the following 3 operations permitted on a word:

Insert a character
Delete a character
Replace a character

Input: word1 = "horse", word2 = "ros"
Output: 3
Explanation: 
horse -> rorse (replace 'h' with 'r')
rorse -> rose (remove 'r')
rose -> ros (remove 'e')

**Comment by kamil200** [comment]
please assign this  problem to me.

**Comment by amitagarwalaa57** [comment]
please assign me the task.
