### ISSUE TITLE
Longest Palindromic Substring

### ISSUE THREAD

**Issue by mahakmandlecha** [mahakmandlecha/LeetCoding-Challenge#3]
Given a string s, find the longest palindromic substring in s. You may assume that the maximum length of s is 1000.
Input: "babad"
Output: "bab"
Note: "aba" is also a valid answer.

**Comment by infern018** [comment]
can i work on this?
also, does the language has to be java, or can i submit in c++ ?

**Comment by amitagarwalaa57** [comment]
please assign me i can solve this.

**Comment by Aditi-Roy-coder** [comment]
Please assign this task to me.

**Comment by Muhib007dev** [comment]
I can do this O(n) time complexity. Assign me I will complete this.
