### ISSUE TITLE
Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by mahakmandlecha** [mahakmandlecha/LeetCoding-Challenge#4]
Given a string s, find the length of the longest substring without repeating characters.

Input: s = "abcabcbb"
Output: 3
Explanation: The answer is "abc", with the length of 3

**Comment by ronanren** [comment]
Can I be assigned to this task?

**Comment by XIZT07** [comment]
can i take this?

**Comment by amitagarwalaa57** [comment]
assign me i can solve this.

**Comment by Aditi-Roy-coder** [comment]
Can you please assign this task to me?
