### ISSUE TITLE
Course Schedule IV

### ISSUE THREAD

**Issue by mahakmandlecha** [mahakmandlecha/LeetCoding-Challenge#5]
There are a total of n courses you have to take, labeled from 0 to n-1.

Some courses may have direct prerequisites, for example, to take course 0 you have first to take course 1, which is expressed as a pair: [1,0]

Given the total number of courses n, a list of direct prerequisite pairs and a list of queries pairs.

You should answer for each queries[i] whether the course queries[i][0] is a prerequisite of the course queries[i][1] or not.

Return a list of boolean, the answers to the given queries.

Please note that if course a is a prerequisite of course b and course b is a prerequisite of course c, then, course a is a prerequisite of course c.

Input: n = 2, prerequisites = [[1,0]], queries = [[0,1],[1,0]]
Output: [false,true]
Explanation: course 0 is not a prerequisite of course 1 but the opposite is true.

**Comment by Ajay0511** [comment]
@mahakmandlecha Please assign this to me.

**Comment by mahakmandlecha** [comment]
Sure
